resolution: workspace
name: features_webview_presentation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  common_presentation: ^0.0.1
  flutter_modular: ^6.4.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  open_file: ^3.5.10
  mime: ^2.0.0
  file_picker: ^10.3.3

dev_dependencies:

flutter:
  generate: true
  uses-material-design: true