name: features_webview_presentation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  common_presentation:
  flutter_modular: ^6.3.4
  widgets_modifiers: ^0.3.42
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  open_file: ^3.5.10
  mime: ^2.0.0
  file_picker: ^8.1.6

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true