name: features_reddit_posts_presentation
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  features_reddit_posts_domain:
    path: "../domain"
  common_presentation:
    path: "../../../common/presentation"
  common_domain:
    path: "../../../common/domain"
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.3.2
  transparent_image: 2.0.1
  flutterui_modifiers: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true