include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
    invalid_annotation_target: ignore

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    invalid_annotation_target: ignore