#  https://github.com/cfug/dio/issues/1653#issuecomment-1619001341
global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator