name: experiments_flutter

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    hooks:
      post: melos run prebuild

scripts:
  prebuild:
    run: |
      melos exec --depends-on="build_runner"          -- dart run build_runner build --delete-conflicting-outputs
      melos exec --depends-on="flutter_localizations" -- flutter gen-l10n