name: experiments_flutter

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    hooks:
      post: melos run prebuild

    environment:
      sdk: ^3.5.4
    dependencies:
      # Common
      flutter_modular: ^6.3.4
      # Presentation
      intl: ^0.19.0
      flutter_bloc: ^8.1.6
      widgets_modifiers: ^0.3.42
      # Data
      freezed_annotation: ^2.4.4
      json_annotation: ^4.9.0
      retrofit: ^4.4.2
      dio: ^5.7.0
      drift: ^2.23.0 # For web after changing version run sh scripts/download_drift_for_web.sh
      drift_flutter: ^0.2.4

    dev_dependencies:
      flutter_lints: ^5.0.0
      build_runner: ^2.4.14
      freezed: ^2.5.7
      json_serializable: ^6.8.0
      retrofit_generator: ^9.1.7
      drift_dev: ^2.23.0
      bloc_test: ^9.1.7
      mocktail: ^1.0.4

scripts:
  prebuild:
    run: |
      melos run build_runner
      melos run flutter_localizations

  prebuild:web:
    run: |
      melos run prebuild
      dart scripts/download_drift_for_web.dart

  pub_get:
    exec: dart pub get

  pub_upgrade:
    exec: dart pub upgrade --major-versions --tighten

  build_runner:
    packageFilters:
      dependsOn:
        - build_runner
    exec: dart run build_runner build --delete-conflicting-outputs

  build_runner_changed:
    packageFilters:
      dependsOn:
        - build_runner
      diff: "origin/master...HEAD"
    exec: dart run build_runner build --delete-conflicting-outputs

  flutter_localizations:
    packageFilters:
      dependsOn:
        - flutter_localizations
    exec: flutter gen-l10n

  set_version:
    run: dart scripts/set_version.dart

  test:
    packageFilters:
      dirExists:
        - test
    exec: flutter test

  ui_test:ios:
    run: |
      melos run build:ios_simulator
      sh apps/app_main/ui_tests/scripts/run_ios.sh

  ui_test:android:
    run: |
      melos run build:android_apk
      sh apps/app_main/ui_tests/scripts/run_android.sh

  deploy:android:firebase_app_distribution:
    run: |
      cd apps/app_main/android
      ./gradlew assembleRelease appDistributionUploadRelease

  build:ios_simulator:
    run: |
      cd apps/app_main/
      flutter build ios --simulator

  build:android_apk:
    run: |
      cd apps/app_main/
      flutter build apk