name: experiments_flutter

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    hooks:
      post: melos run prebuild

scripts:
  prebuild:
    run: |
      melos run build_runner
      melos run flutter_localizations

  prebuild:web:
    run: |
      melos run prebuild
      dart scripts/download_drift_for_web.dart

  pub_get:
    exec: dart pub get

  pub_upgrade:
    exec: pub upgrade --major-versions --tighten

  build_runner:
    packageFilters:
      diff: "origin/main...HEAD"
      dependsOn:
        - build_runner
    exec: dart run build_runner build --delete-conflicting-outputs

  build_runner_changed:
    packageFilters:
      dependsOn:
        - build_runner
      diff: "origin/master...HEAD"
    exec: dart run build_runner build --delete-conflicting-outputs

  flutter_localizations:
    packageFilters:
      dependsOn:
        - flutter_localizations
    exec: flutter gen-l10n

  set_version:
    run: dart scripts/set_version.dart

  test:
    packageFilters:
      dirExists:
        - test
    exec: flutter test