name: my_project

environment:
  sdk: ^3.8.0

workspace:
  - packages/common/data
  - packages/common/domain
  - packages/common/presentation
  - packages/features/experiments/presentation
  - packages/features/firebase_chat/presentation
  - packages/features/forms/presentation
  - packages/features/home/presentation
  - packages/features/reddit_posts/data
  - packages/features/reddit_posts/domain
  - packages/features/reddit_posts/presentation
  - packages/features/stackoverflow/presentation
  - packages/features/weather/data
  - packages/features/weather/domain
  - packages/features/weather/presentation
  - packages/features/webview/presentation
  - packages/features/timelapse/presentation
  - apps/app_main

dev_dependencies:
  melos: ^7.4.0

melos:
  packages:
    - apps/**
    - packages/**

  command:
    bootstrap:
      hooks:
        post: melos run prebuild

      environment:
        sdk: ^3.8.0
      dependencies:
        # Common
        injectable: ^2.7.1+4
        get_it: ^9.2.1
        rxdart: ^0.28.0
        auto_route: ^11.1.0
        # Presentation: System
        intl: ^0.20.2
        cupertino_icons: ^1.0.8
        # Presentation: Patterns
        bloc: ^9.1.0
        flutter_bloc: ^9.1.1
        hydrated_bloc: ^10.1.1
        flutter_hooks: ^0.21.3+1
        hooks_riverpod: ^3.2.1
        riverpod_annotation: ^4.0.2
        # Presentation: Native
        geolocator: ^14.0.2
        safe_device: ^1.3.8
        file_picker: ^10.3.3
        image_picker: ^1.2.0
        path_provider: ^2.1.5
        url_launcher: ^6.3.2
        open_file: ^3.5.10
        mime: ^2.0.0
        shared_preferences: ^2.5.3
        # Presentation: Google
        firebase_auth: ^5.0.0
        firebase_core: ^3.0.0
        firebase_messaging: ^15.0.0
        # Presentation: UI
        html: ^0.15.6
        transparent_image: 2.0.1
        internet_connection_checker_plus: ^2.9.0
        shimmer: ^3.0.0
        formz: ^0.8.0
        flutter_view_modifiers: 0.0.9
        flutter_inappwebview: ^6.1.5
        flutter_staggered_grid_view: ^0.7.0
        flutter_chat_core: ^2.8.0
        flutter_chat_ui: ^2.9.1
        flutter_firebase_chat_core: ^1.6.8
        flutter_local_notifications: ^19.5.0

        # Data
        freezed_annotation: ^3.0.0
        json_annotation: ^4.9.0
        retrofit: ^4.8.0
        dio: ^5.9.0
        dio_cache_interceptor: ^4.0.5
        flutter_secure_storage: ^9.2.4
        drift: ^2.23.0
        drift_flutter: ^0.2.4
        # For web after changing drift version run sh scripts/download_drift_for_web.sh

      dev_dependencies:
        flutter_lints: ^6.0.0
        build_runner: ^2.12.2
        freezed: ^3.0.0
        json_serializable: ^6.11.1
        retrofit_generator: ^10.0.0
        drift_dev: ^2.23.0
        bloc_test: ^10.0.0
        mocktail: ^1.0.4
        riverpod_generator: ^4.0.3
        auto_route_generator: ^10.4.0
        injectable_generator: ^2.12.1

  scripts:
    prebuild:
      run: |
        melos run build_runner
        melos run flutter_localizations

    prebuild:web:
      run: |
        melos run prebuild
        dart scripts/download_drift_for_web.dart

    pub_get:
      exec: dart pub get

    pub_upgrade:
      exec: dart pub upgrade --major-versions --tighten

    build_runner:
      packageFilters:
        dependsOn:
          - build_runner
      run: dart run build_runner build --delete-conflicting-outputs
      exec:
        concurrency: 1

    build_runner_changed:
      packageFilters:
        dependsOn:
          - build_runner
        diff: "origin/master...HEAD"
      exec: dart run build_runner build --delete-conflicting-outputs

    flutter_localizations:
      packageFilters:
        dependsOn:
          - flutter_localizations
      run: flutter gen-l10n
      exec:
        concurrency: 1

    set_version:
      run: dart scripts/set_version.dart

    test:
      packageFilters:
        dirExists:
          - test
      exec: flutter test

    ui_test:ios:
      run: |
        melos run build:ios_simulator
        sh apps/app_main/ui_tests/scripts/setup.sh
        sh apps/app_main/ui_tests/scripts/run_ios.sh

    ui_test:android:
      run: |
        melos run build:android_apk
        sh apps/app_main/ui_tests/scripts/setup.sh
        sh apps/app_main/ui_tests/scripts/run_android.sh

    deploy:android:firebase_app_distribution:
      run: |
        cd apps/app_main/android
        ./gradlew assembleRelease appDistributionUploadRelease

    build:ios_simulator:
      run: |
        cd apps/app_main/
        flutter build ios --simulator

    build:android_apk:
      run: |
        cd apps/app_main/
        flutter build apk