name: features_forms_presentation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  common_presentation:
    path: "../../../common/presentation"
  flutter_bloc: ^8.1.6
  flutter_modular: ^6.3.4
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  file_picker: ^8.0.5
  rxdart: ^0.28.0
  image_picker: ^1.1.2
  widgets_modifiers: ^0.3.42

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2

flutter:
  generate: true
  uses-material-design: true