resolution: workspace
name: features_stackoverflow_presentation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.4.1
  dio: ^5.9.0
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.6.1
  html: ^0.15.5
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.3

flutter: