resolution: workspace
name: features_reddit_posts_domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.4.1
  common_domain: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: