resolution: workspace
name: features_home_presentation
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^8.1.6
  flutter_modular: ^6.4.1
  common_presentation: ^0.0.1
  features_weather_presentation: ^0.0.1
  features_reddit_posts_presentation: ^0.0.1
  features_forms_presentation: ^0.0.1
  features_webview_presentation: ^0.0.1
  features_experiments_presentation: ^0.0.1
  features_stackoverflow_presentation: ^0.0.1
  features_firebase_chat_presentation: ^0.0.1
  flutter_view_modifiers: 0.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true