resolution: workspace
name: features_home_presentation
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  flutter_modular: ^6.4.1
  common_presentation:
  features_weather_presentation:
  features_reddit_posts_presentation:
  features_forms_presentation:
  features_webview_presentation:
  features_experiments_presentation:
  features_stackoverflow_presentation:
  features_firebase_chat_presentation:
  flutter_view_modifiers: 0.0.9
  auto_route: ^11.1.0

flutter:
  generate: true
  uses-material-design: true

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.4.14