resolution: workspace
name: common_presentation
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^8.1.6
  internet_connection_checker_plus: ^2.7.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true