name: features_weather_domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  flutter_lints: ^4.0.0

flutter:
