resolution: workspace
name: features_firebase_chat_presentation
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  common_presentation:
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter:
    sdk: flutter
  flutter_chat_ui: ^2.9.1
  flutter_firebase_chat_core: ^1.6.8
  flutter_local_notifications: ^19.5.0
  flutter_view_modifiers: 0.0.9
  auto_route: ^11.1.0

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.12.2

flutter: