name: features_firebase_chat_presentation
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4

dependencies:
  common_presentation: ^0.0.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.15
  flutter_firebase_chat_core: ^1.6.8
  flutter_local_notifications: ^18.0.1
  flutter_modular: ^6.3.4
  widgets_modifiers: ^0.3.42

dev_dependencies:
  flutter_lints: ^5.0.0

flutter: