name: modular_app
description: Modular App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  flutter_modular: ^6.3.4
  safe_device: ^1.1.9
  common_presentation: ^0.0.1
  features_home_presentation: ^0.0.1
  features_weather_domain: ^0.0.1
  features_weather_data: ^0.0.1
  features_weather_presentation: ^0.0.1
  features_reddit_posts_domain: ^0.0.1
  features_reddit_posts_data: ^0.0.1
  features_reddit_posts_presentation: ^0.0.1
  features_forms_presentation: ^0.0.1
  features_webview_presentation: ^0.0.1
  features_experiments_presentation: ^0.0.1
  features_stackoverflow_presentation: ^0.0.1
  features_firebase_chat_presentation: ^0.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true