resolution: workspace
name: modular_app
description: Modular App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  injectable: ^2.7.1+4
  get_it: ^9.2.1
  safe_device: ^1.3.8
  common_presentation:
  common_data:
  features_home_presentation: ^0.0.1
  features_weather_domain:
  features_weather_data: ^0.0.1
  features_weather_presentation: ^0.0.1
  features_reddit_posts_domain:
  features_reddit_posts_data: ^0.0.1
  features_reddit_posts_presentation: ^0.0.1
  features_forms_presentation: ^0.0.1
  features_webview_presentation: ^0.0.1
  features_experiments_presentation: ^0.0.1
  features_stackoverflow_presentation: ^0.0.1
  features_firebase_chat_presentation: ^0.0.1
  cupertino_icons: ^1.0.8
  auto_route: ^11.1.0

dev_dependencies:
  injectable_generator: ^2.12.1
  build_runner: ^2.12.2

flutter:
  uses-material-design: true