resolution: workspace
name: features_timelapse_presentation
description: "A new Flutter package project for Timelapse feature."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  common_presentation:
  intl: ^0.20.2
  auto_route: ^11.1.0
  injectable: ^2.7.1+4
  get_it: ^9.2.1
  wakelock_plus: ^1.2.11
  path_provider: ^2.1.5
  camera: ^0.11.1
  image: ^4.8.0

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.12.2
  injectable_generator: ^2.12.1

flutter:
  generate: true
  uses-material-design: true
