name: deploy_app

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install project dependencies
        run: sh scripts/pub_get_all.sh

      - name: Deploy web app
        uses: bluefireteam/flutter-gh-pages@v7