name: deploy_web

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Flutter Doctor
        run: flutter doctor

      - name: Install Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run:
          dart run melos bootstrap
          dart run melos run prebuild:web

      - name: Deploy web
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /Experiments-flutter/
