name: unit_tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install project dependencies
        run: sh scripts/pub_get_all.sh

      - name: Localizations
        run: sh scripts/generate_translate_file.sh

      - name: Build Runner
        run: sh scripts/build_runner.sh

      - name: Run unit tests
        run: sh scripts/run_tests.sh