name: unit_tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Flutter Doctor
        run: flutter doctor

      - name: Install Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run: dart run melos bootstrap

      - name: Run unit tests
        run: dart run melos run test